- hosts: all
  sudo: True
  user: vagrant
  vars_files:
    - vars/mysql.yml
  roles:
    - common
    - mysql
    - php
    - nginx
    - wordpress
  vars:
    mysql_root_password: root
    mysql_wp_user: wordpress
    mysql_wp_password: wordpress
    wordpress_db_name: wordpress

  tasks:
    - name: "Instala MySQL"
      apt: name=mysql-server state=latest install_recommends=yes

    - name: "Instala extensoes do MySQL para Python"
      apt: name=python-mysqldb state=latest install_recommends=yes

#    - name: "Apaga o site default"
#      file: path=/etc/nginx/sites-available/default recurse=yes state=abstent

    - name: "Reinicia NGINX"
      service: name=nginx state=restarted

    - name: "Cria /opt/wordpress"
      file: dest=/opt/wordpress mode=755 state=directory owner=www-data

    - name: "Download do Wordpress"
      get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/latest.tar.gz

    - name: "Abre wordpress em /opt/wordpress"
      unarchive: src=/tmp/latest.tar.gz dest=/opt copy=no

    - name: "Corrige permissoes"
      file: path=/opt/wordpress recurse=yes owner=www-data group=www-data

    - name: "Inicia MySQL"
      service: name=mysql state=restarted sleep=2

    - name: "Cria .my.cnf"
      template: src=my.cnf.j2 dest=~/.my.cnf mode=0600

    - name: "Cria senha de root para root@mysql"
      mysql_user: name=root password="{{ mysql_root_password }}" check_implicit_admin=yes priv="*.*:ALL,GRANT" state=present host="{{ item }}"
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: "Cria wordpress database"
      mysql_db: name=wordpress login_user=root login_password="{{ mysql_root_password }}" state=present

    - name: "Cria usuario wordpress"
      mysql_user: name="{{ mysql_wp_user }}" password="{{ mysql_wp_password }}" priv="{{ wordpress_db_name }}.*:ALL" check_implicit_admin=yes login_user=root login_password="{{ mysql_root_password }}" host="{{ item }}" state=present
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
